spring:
  application:
    name: x_ray.app
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: bitBuilderdb
      auto-index-creation: true
  servlet:
    multipart:
          enabled: true
          max-file-size: 20MB
          max-request-size: 25MB
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
springdoc:
  swagger-ui:
    path: /

ai:
  url: https://impuissant-electrochemically-brande.ngrok-free.dev/predict

blockchain:
  rpc-url: https://rpc-amoy.polygon.technology
  private-key: 0x3e115957920795443451bb4337d150f0d7c49a55c9265db59132c7b52684764b
  contract-address: 0xf1aC91da59d8926401188Eb21F43e3614BDE4Ef2