spring:
  application:
    name: x_ray.app
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: bitBuilderdb
      auto-index-creation: true
  servlet:
    multipart:
          enabled: true
          max-file-size: 20MB
          max-request-size: 25MB
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
springdoc:
  swagger-ui:
    path: /

ai:
  url: https://impuissant-electrochemically-brande.ngrok-free.dev/predict
