spring:
  application:
    name: x_ray.app
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: bitBuilderdb
      auto-index-creation: true
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
springdoc:
  swagger-ui:
    path: /